services:
  - type: web
    name: uai-manutencao
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
    disk:
      name: data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
